### PR TITLE
Better stream

### PR DESCRIPTION
**Pull request by dnomadb**
I re-did the logic in a much cleaner fashion. Before merging:
- [ ] Modularize in / out so that it can accept arrays asynchronously
- [ ] Move output to CLI handler (ie, make tri-zilla not assume output type)
- [ ] Write a barrage of tests; expected outputs, expected errors, other issues
- [x] Check for other silliness a la https://github.com/mapbox/tri-zilla/commit/37cd49ee29b0b859070a7204d98372148c7f4ad7

cc: @ian29

### CODE REVIEW

**Comment by ian29** [comment]
cool! @dnomadb can u say more about 

> Move output to CLI handler (ie, make tri-zilla not assume output type)
1. what do u mean
2. is this smth i can help with?

**Comment by dnomadb** [comment]
1. Like, trizilla should just take an index: {} and inflate and aggregate, whether it is from a stdin stream, or called asynchronously on an array. I can elaborate when I am in.
2. Yes plz!

**Comment by ian29** [comment]
oh oh oh i think i understand :100:

**Comment by ian29** [comment]
gonna merge this. let's capture follow up / in separate tickets. @dnomadb

**Pull request merged**
